### ISSUE TITLE
[AC::OJ] A sandbox for linux

### ISSUE THREAD

**Issue by ProjectDimlight** [Chenyao2333/syzoj#3]
https://github.com/ProjectAC/ACJudge  <- This is my judge system. You can learn how a sandbox is built.

**Comment by louchenyao** [comment]
Thanks.
I don't have enough free time for this project now. Maybe someday I will continue to develop SYZOJ, I will rewrite Sandbox or directly use other Sandboxes (like ACJudge :).

**Comment by fybmain** [comment]
As a responsible system guard who highly concerns the safety and security of an online judge system,I am very excited to find this project and have decided to apply it to my new online judge system.Well,I'd like to say thanks.

**Comment by fybmain** [comment]
However, what I have to remind you is the disadvantages of choosing a wild license such as WTFPL. Choosing such a permission license means not only everyone can copy and modify it without any limitations, but also there will be no guaranteed rewards even if the code is used all over the world, on fame or any other things, for anyone can copy codes that is written by a contributor day and night, and then rename it as if the project were their own masterpiece, or directly make it a NON-FREE project. This will make many potential contributors lose the intention to contribute codes to your project.

**Comment by fybmain** [comment]
By the way, the WTFPL does NOT include a no-warranty disclaimer.Please add one manually, for I believe that you are not willing to receive a summons from the court for this project.

**Comment by ProjectDimlight** [comment]
However this is just exactly what the f**k I want. Thanks for your reminding though.
