### ISSUE TITLE
编译时的安全问题

### ISSUE THREAD

**Issue by Ruanxingzhi** [Chenyao2333/syzoj#8]
http://syzoj.com/judge_detail/8957
http://syzoj.com/judge_detail/8968

这怎么办办啊……

**Comment by Fmuckss** [comment]
我编译因为不太清楚会有什么系统调用就没有加沙箱 ( 懒 ) ，然后你猜我为什么要限制编译报错信息长度 ( 逃

**Comment by TimHsue** [comment]
我编译因为不太清楚会有什么系统调用就没有加沙箱 ( 懒 ) ，然后你猜我为什么要限制编译报错信息长度 ( 逃 ( 刚才不小心登错号了，要是收到两份邮件无视掉一份就好 ( 再逃

**Comment by louchenyao** [comment]
似乎限制长度，并不能解决这个问题。。。。（思考熊.jpg
@TimHsue

**Comment by TimHsue** [comment]
这个长度刚好解决所有问题，欢迎测试 ( 捂脸熊.jpg
@Chenyao2333

**Comment by Menci** [comment]
以 nobody 用户编译就不会有问题了

**Comment by TimHsue** [comment]
嗯... 其实，评测和服务器现在是隔离的，再加上长度限制应该get不到什么关键信息的0.0.....
@Menci
